### ISSUE TITLE
BB REST API : Activity Comment - PHP Fatal Error: Uncaught ArgumentCountError: Too few arguments bp_blogs_activity_comment_content_with_read_more

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1812]
**Describe the bug**
With the latest version of BuddyBoss, there's a PHP Fatal Error when you try to post comment using BB REST API.

```
[21-Nov-2020 10:32:41 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function bp_blogs_activity_comment_content_with_read_more(), 1 passed in /opt/htdocs/wp-includes/class-wp-hook.php on line 287 and exactly 2 expected in /opt/htdocs/wp-content/plugins/buddyboss-platform/bp-activity/bp-activity-filters.php:2348
Stack trace:
#0 /opt/htdocs/wp-includes/class-wp-hook.php(287): bp_blogs_activity_comment_content_with_read_more()
#1 /opt/htdocs/wp-includes/plugin.php(206): WP_Hook->apply_filters()
#2 /opt/htdocs/wp-content/plugins/buddyboss-platform/bp-activity/classes/class-bp-rest-activity-endpoint.php(1101): apply_filters()
#3 /opt/htdocs/wp-content/plugins/buddyboss-platform/bp-activity/classes/class-bp-rest-activity-endpoint.php(1171): BP_REST_Activity_Endpoint->render_item()
#4 /opt/htdocs/wp-content/plugins/buddyb in /opt/htdocs/wp-content/plugins/buddyboss-platform/bp-activity/bp-activity-filters.php on line 2348
```

**To Reproduce**
```
Entête : POST /wp-json/buddyboss/v1/activity/1218/comment HTTP/1.1
Données : { "content":"Test Comment", "parent_id":1218 }
```

**Expected behavior**
none

**Screenshots**
none

**Support ticket links**
none

**Comment by ExoGeek** [comment]
Resolving this issue seems quite simple. Modify the file **class-bp-rest-activity-endpoint.php**, function **render_item** (line **1101**) :

From
`$rendered = apply_filters( 'bp_get_activity_content', $activity->content );`
To
`$rendered = apply_filters( 'bp_get_activity_content', $activity->content, $activity );`

Regards
