### ISSUE TITLE
Undefined function symlink() error when server doesn't support symlink

### ISSUE THREAD

**Issue by kent-carlo** [buddyboss/buddyboss-platform#2974]
**Describe the bug**
The issue happens when updating plugin versions 1.7.6 above. Error appears everytime **bb_core_enable_default_symlink_support** function is being executed. In addition, error occurs regardless if bp_media_symlink_support is enabled or not.

**To Reproduce**
1. Make sure to test it on the server that doesn't support symlink.
2. Use platform plugin version 1.7.6 above.
3. Activate the plugin and see the error.
4. If ever you see no error when activating the plugin, try deactivating the activity component and activate it back.

**Expected behavior**
Regardless if the symlink is supported or not, there should be no error showing.

**Screenshots**
https://www.awesomescreenshot.com/video/5368585?key=e2397b6fde4051f60afc73b79a385a35

**Environment**
Which site did you replicate this issue on? 
CX's site with no other plugins activated

**Support ticket links**
https://secure.helpscout.net/conversation/1632096423/164198/

**Comment by surajkrsingh** [comment]
Found similar issue - https://secure.helpscout.net/conversation/1639953834/165524?folderId=3709082
The customer has kinsta server

`An error of type E_ERROR was caused in line 5765 of the file /www/hercyberspace_790/public/wp-content/plugins/buddyboss-platform/bp-core/bp-core-functions.php. Error message: Uncaught Error: Call to undefined function symlink() in /www/hercyberspace_790/public/wp-content/plugins/buddyboss-platform/bp-core/bp-core-functions.php:5765 Stack trace: #0 /www/hercyberspace_790/public/wp-content/plugins/buddyboss-platform/bp-core/admin/bp-core-admin-schema.php(90): bb_core_enable_default_symlink_support() #1 /www/hercyberspace_790/public/wp-content/plugins/buddyboss-platform/bp-core/bp-core-update.php(225): bp_core_install() #2 /www/hercyberspace_790/public/wp-content/plugins/buddyboss-platform/bp-core/bp-core-update.php(156): bp_version_updater() #3 /www/hercyberspace_790/public/wp-includes/class-wp-hook.php(303): bp_setup_updater('') #4 /www/hercyberspace_790/public/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(false, Array) #5 /www/hercyberspace_790/public/wp-includes/plugin.php(470): WP_Hook->do_action(Array) #6 /www/hercyberspace_790/public/wp-content/plugins/buddyboss-platform/bp-core/admin/bp-core-admin-actions.php(126): do_action('bp_admin_init') #7 /www/hercyberspace_790/public/wp-includes/class-wp-hook.php(303): bp_admin_init('') #8 /www/hercyberspace_790/public/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array) #9 /www/hercyberspace_790/public/wp-includes/plugin.php(470): WP_Hook->do_action(Array) #10 /www/hercyberspace_790/public/wp-admin/admin.php(175): do_action('admin_init') #11 /www/hercyberspace_790/public/wp-admin/plugins.php(10): require_once('/www/hercybersp...') #12 {main} thrown`
