### ISSUE TITLE
Bugs related to commonly disabled php functions: Group delete results in cron execution timeout + repair documents hangs + unpredictable symlink functionality

### ISSUE THREAD

**Issue by ev0net** [buddyboss/buddyboss-platform#3152]
php functions: system() + symlink() are commonly disabled by hosts. Apparently lack of admin notification or graceful handling of these functions seem to result in the following three bugs:

1. Group delete results in cron execution timeout (SEE ADDITIONAL INFO IN COMMENT BELOW)
- if php system() is disabled, 
- group delete results in fatal error
- which in turn inserts similar code in wp_options table: (45245, 'wp_1_bp_updater_batch_0d952a28a32661728bcf9469d5eaa5fa', 'a:1:{i:0;a:2:{s:8:\"callback\";a:2:{i:0;O:16:\"BP_Suspend_Forum\":3:{s:17:\"backgroup_diabled\";b:0;s:9:\"item_type\";s:5:\"forum\";s:5:\"alias\";s:1:\"s\";}i:1;s:20:\"hide_related_content\";}s:4:\"args\";a:3:{i:0;i:0;i:1;b:0;i:2;a:2:{s:12:\"blocked_user\";s:0:\"\";s:14:\"user_suspended\";b:0;}}}}', 'no');
- which causes cron jobs to to hang and cause execution timeout errors or processes that run indefinitely
- FIX: message stating system() must be enabled AND do not allow group deletion before enabled.

`NUM/TYPE: 		1/E_ERROR
FILE:     		/home/site/public_html/wp-content/plugins/buddyboss-platform/bp-groups/classes/class-bp-groups-group.php
LINE:     		426
MESSAGE:  		Uncaught Error: Call to undefined function system() in /home/site/public_html/wp-content/plugins/buddyboss-platform/bp-groups/classes/class-bp-groups-group.php:426
Stack trace:
#0 /home/site/public_html/wp-content/plugins/buddyboss-platform/bp-groups/bp-groups-functions.php(476): BP_Groups_Group->delete()
#1 /home/site/public_html/wp-content/plugins/buddyboss-platform/bp-groups/bp-groups-admin.php(129): groups_delete_group()
#2 /home/site/public_html/wp-includes/class-wp-hook.php(292): bp_groups_admin_load()
#3 /home/site/public_html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters()
#4 /home/site/public_html/wp-includes/plugin.php(484): WP_Hook->do_action()
#5 /home/site/public_html/wp-admin/admin.php(237): do_action()
#6 {main}
  thrown`

2. repair documents hangs
- if php symlink() is disabled, 
- wp-admin > buddyboss > tools > repair community > repair document on site causes fatal error and indefinitely spinning "working" icon
- FIX: message stating symlink() must be enabled AND do not allow selection if disabled

`REQUEST_URI:  	/wp-admin/admin-ajax.php
HTTP_REFFER:  	https://site.com/wp-admin/admin.php?page=bp-repair-community&tab=bp-repair-community
NUM/TYPE: 		1/E_ERROR
FILE:     		/home/site/public_html/wp-content/plugins/buddyboss-platform/bp-core/bp-core-functions.php
LINE:     		5611
MESSAGE:  		Uncaught Error: Call to undefined function symlink() in /home/site/public_html/wp-content/plugins/buddyboss-platform/bp-core/bp-core-functions.php:5611
Stack trace:
#0 /home/site/public_html/wp-content/plugins/buddyboss-platform/bp-document/bp-document-functions.php(3711): bb_core_symlink_generator()
#1 /home/site/public_html/wp-includes/class-wp-hook.php(292): bp_document_create_symlinks()
#2 /home/site/public_html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters()
#3 /home/site/public_html/wp-includes/plugin.php(551): WP_Hook->do_action()
#4 /home/site/public_html/wp-content/plugins/buddyboss-platform/bp-document/classes/class-bp-document.php(1971): do_action_ref_array()
#5 /home/site/public_html/wp-content/plugins/buddyboss-platform/bp-document/bp-document-filters.php(1550): BP_Document->save()
#6 /home/site/public_html/wp-content/plugins/buddyboss-platform/bp-core/admin/bp-core-admin-tools.php(1134): bp_document_admin_repair_document()
#7 /home/site/public_html/wp-includes/class-wp-hook.php(292): bp_admin_repair_tools_wrapper_function()
#8 /home/site/public_html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters()
#9 /home/site/public_html/wp-includes/plugin.php(484): WP_Hook->do_action()
#10 /home/site/public_html/wp-admin/admin-ajax.php(187): do_action()
#11 {main}
  thrown`

3. unpredictable symlink setting functionality
- if php symlink() is disabled, 
- buddyboss > settings > media > Media Security & Performance > Symbolic Links > checked states symbolic links are activated but do not work
- FIX: message stating symlink() must be enabled and do not allow selection if disabled.

**Comment by ev0net** [comment]
Update regarding item 1: 

I'm getting cron execution timeout errors upon group creation with or without system() enabled. I'm "fixing" it by searching for "backgroup_diabled" in wp_options. Group creation inserts a record similar to:

(45245, 'wp_1_bp_updater_batch_0d952a28a32661728bcf9469d5eaa5fa', 'a:1:{i:0;a:2:{s:8:"callback";a:2:{i:0;O:16:"BP_Suspend_Forum":3:{s:17:"backgroup_diabled";b:0;s:9:"item_type";s:5:"forum";s:5:"alias";s:1:"s";}i:1;s:20:"hide_related_content";}s:4:"args";a:3:{i:0;i:0;i:1;b:0;i:2;a:2:{s:12:"blocked_user";s:0:"";s:14:"user_suspended";b:0;}}}}', 'no');

Deleting that record stops cron execution timeout error. 

How the cron triggered wp_1_bp_updater_cron is interacting with the above wp_options record appears to be causing an infinite loop.
